### ISSUE TITLE
Progress bar on Fully minted SRC-20 Tokens should not display a mint progress

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#140]
in the wallet page: /wallet/bc1qhhv6rmxvq5mj2fc3zne2gpjqduy45urapje64m

The items that have been fully minted should not show a mint button nor a progress bar. 

Also the images are not displaying properly for SRC-20 tokens on this page

![image](https://github.com/user-attachments/assets/294773d5-55ba-4728-8e7e-f2223cd3c356)

**Comment by eliot1011** [comment]
Added the filters into that function so that if progress is 100%, mint button & progress won't display: #140

**Comment by reinamora137** [comment]
the formatting seems to have changed, but the 100% minted out tokens still display a progress bar and the others are showing no progress

![image](https://github.com/user-attachments/assets/2ebd5e41-ae0a-4e27-ae24-85fc09c284d0)


this is the current design without the progress bar, but ones that are fully minted do not show the mint button:

![image](https://github.com/user-attachments/assets/bf46dae5-17e0-422c-b44b-cdabc3cc01ec)

also there should be a listings section on the wallet page which will be both dispensers owned by the user and atomic swap open orders. we can pull open dispenser data on the user, but this design can be a placeholder and i'll create a new issue to pull in the data here properly

![image](https://github.com/user-attachments/assets/6b6ea3c2-faef-4423-84ca-c6b5d2909bb7)

**Comment by reinamora137** [comment]
related to #174
