### ISSUE TITLE
Social media link images for SRC-20 Tokens should not display if they are null 

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#141]
The email/web/TG/X should not display when these values are not in the data (which is almost all tokens at the moment)

/src20 page

![image](https://github.com/user-attachments/assets/7f66cb0c-08dd-4960-947a-baae70dfa3de)

**Comment by eliot1011** [comment]
Add the filter conditions for social icons with email/web/TG/X about each item: #141
