### ISSUE TITLE
Styling on /home does not match figma

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#143]
The styling on the headers does not match expected on /home. larger gap between sub-heading and wrong styling on the 'latest art stamps' etc.

Current:

![image](https://github.com/user-attachments/assets/ffe0a119-5cbd-4cae-a333-a0f1ed8b92cd)

Figma: 
![image](https://github.com/user-attachments/assets/31a8c56f-4179-4552-b037-cec6d8a2ea2c)

**Comment by eliot1011** [comment]
Updated the text like figma with gradient : #144

**Comment by babalicious-io** [comment]
Please note the homepage figma design is not yet finished !

**Comment by reinamora137** [comment]
closing for now to revisit when home page design is complete. the gradient and hamburger look correct for now
