### ISSUE TITLE
Gutter on /home stamp displays is resizing incorrectly on breakpoints it appears

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#144]
![image](https://github.com/user-attachments/assets/edff0b5b-be74-4bdd-aa71-2d3aeb4cbe26)

I believe the intention here is the image containers scale, not the gutters in between

**Comment by eliot1011** [comment]
I set the min width for this and remove the empty space between items.

**Comment by reinamora137** [comment]
related to #171

**Comment by babalicious-io** [comment]
Looks good, but I need the Art Stamps Overview page (the stampcards more specifically) updated to figma design, to be able to properly check that the gutter spacing (and left/right margin) is correct.
