### ISSUE TITLE
New Carousel Images, Remove Border from static images, scaling off on mobile with the status bars - - - - - below the image

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#148]
The carousel should have 5 images. EDIT: images to add below are provided. they may need resizing to match the others. 

[EDIT] 5 images were added, but a few minor tweaks needed in particular for the mobile display showing a big gap below the carousel and more than 5 of the. - - - - - dashes below the image. 

Figma: 
![image](https://github.com/user-attachments/assets/a8f61b10-c0cf-49d4-a4c7-39256b92f88e)

**Comment by StampBlaster5000** [comment]
![A1214836277016351800](https://github.com/user-attachments/assets/24284876-8e0c-4075-a29c-767feb9c775e)
<img width="1974" alt="btc_socks" src="https://github.com/user-attachments/assets/7c750f28-a454-4929-b1af-bc572cf9018b">
![Avime](https://github.com/user-attachments/assets/e899c352-bad6-411b-90a1-a3835331a7aa)

**Comment by babalicious-io** [comment]
The 5 stamp image carousel is wip
I haven’t finished it off. It should be ready for desktop and tablet, but I haven’t done the mobile versions, nor double checked the ones done.
Please expect minor finetuning if implemented on dev site.

**Comment by reinamora137** [comment]
The carousel is not auto scrolling now on mobile and the images above were not added on recent PR

**Comment by reinamora137** [comment]
also perhaps some duplication in islands/Carousel.tsx vs islands/Carousel3d.tsx that needs to be resolved
