### ISSUE TITLE
POSH stamp filtering recently broke

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#151]
This appears to have been broken in a recent commit. 

https://dev.bitcoinstamps.xyz/stamp?type=posh

it should be displaying all stamps in the posh collection.

**Comment by eliot1011** [comment]
I think there is no error on frontend side
so we need to check the backend side

**Comment by reinamora137** [comment]
Looks like CollectionId is being pulled. any other debug status?

**Comment by reinamora137** [comment]
fixed on PR: https://github.com/stampchain-io/BTCStampsExplorer/pull/176
