### ISSUE TITLE
Stampcard Details Design Issues #220 #222

### ISSUE THREAD

**Issue by StampBlaster5000** [stampchain-io/BTCStampsExplorer#154]
Explore Stamps - Stamp card Details
Maintain Image scale to view 6 images per row.
Current:
![image](https://github.com/user-attachments/assets/2e3a4417-f097-48b7-b755-29c342eefb03)

Figma File:
![image](https://github.com/user-attachments/assets/ff4fd435-c94f-4e2d-8619-ad83dc8216d1)

**Comment by reinamora137** [comment]
note the display of the details will soon be selectable by the user - likely in V2. There are a few variances on when the details are displayed throughout the site currently.

**Comment by reinamora137** [comment]
The scaling of the # sign in front of the stamp number looks off on mobile. Need to validate against figma design

**Comment by reinamora137** [comment]
Long names for posh stamps scale outside the container:

![image](https://github.com/user-attachments/assets/32923612-ed04-4c3d-a664-6cbed6377b2f)

**Comment by reinamora137** [comment]
related to #220 #222

**Comment by wichopy** [comment]
ill try the long name bug

**Comment by wichopy** [comment]
@reinamora137 this seems fixed by you
