### ISSUE TITLE
Stamp tool mint window does not match figma 

### ISSUE THREAD

**Issue by StampBlaster5000** [stampchain-io/BTCStampsExplorer#155]
Current: Mint Portal does not match Figma, also latest stamps preview images should have src20s filtered out.
![image](https://github.com/user-attachments/assets/318a34ac-ff28-436b-8358-069efd0ee6a1)

Figma:
![image](https://github.com/user-attachments/assets/e1450011-c7f2-44f5-b3fb-adf05945b22e)

**Comment by reinamora137** [comment]
Current Issues:

- Font not capitalized on Faq - vs - FAQ
- Gradient on FAQ
- Font weight on Latest Stamps and Lorem Ipsum (which should just be hidden for now for future use) 
- Font weight and button styling on 'view all' 
- Image scaling across all breakpoints

![image](https://github.com/user-attachments/assets/f899a0c3-8d26-4543-8bf7-f611e29aa432)

**Comment by reinamora137** [comment]
Lorem Ipsum needs to be hidden for future use, and the latest stamps should only filter on 'classic'
