### ISSUE TITLE
Holders not correctly updating on stamp detail page.

### ISSUE THREAD

**Issue by arwyn6969** [stampchain-io/BTCStampsExplorer#158]
<img width="1434" alt="Screenshot 2024-10-25 at 16 31 53" src="https://github.com/user-attachments/assets/50da801d-8a3b-4cbf-b119-d3427da455b0">

**Comment by reinamora137** [comment]
is there more than 1 holder on this stamp? or are you referring to the pie chart breakpoints?

**Comment by reinamora137** [comment]
this may be resolved in:

https://github.com/stampchain-io/BTCStampsExplorer/pull/184/files

**Comment by reinamora137** [comment]
graph currently not displaying on this stamp: 

![image](https://github.com/user-attachments/assets/89646ac5-e02f-4a49-8780-e43ef42917c8)

The amount '21' appears to be hard coded? is this pulling from the holders data properly anymore? 


here is an example of a stamp that does not have 21 editions and has more than 1 holder:

https://dev.bitcoinstamps.xyz/stamp/11

actually has 146 holders as seen in the balances here: 

https://explorer.unspendablelabs.com/assets/A5433937813514022010
