### ISSUE TITLE
STAMP "stamping" error

### ISSUE THREAD

**Issue by arwyn6969** [stampchain-io/BTCStampsExplorer#161]
Failed to fetch stamps balance for UTXO exclusion

**Comment by reinamora137** [comment]
This is related to #160 just on the stamps page so it is impacting both src-20 and stamp UTXO selection

**Comment by reinamora137** [comment]
Also related to: https://github.com/stampchain-io/BTCStampsExplorer/pull/223

**Comment by reinamora137** [comment]
this should be resolved need to validate
