### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#171]
### Header

The dev site is not updated with the figma design on the following:

- **Logo hover state**
https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=4180-2445&m=dev&t=DqgBttaIC7RjH9Yc-1
- **Connect button** 
font-weight: 800;
resizing on tablet
https://github.com/orgs/stampchain-io/discussions/23#discussioncomment-10832303
- the layout of the NavMenus look off on my tablet (should just be one line, no line break) - strangely it views correctly on desktop resized smaller browser window

![IMG_0339 2](https://github.com/user-attachments/assets/e5b7bfe1-1f86-4e4c-9191-a6f562afde3d)

**Mobile overlay menu** 
- Uses slightly different sized layout for large and small mobile
- The icon links also are not correct - we've dropped the envelope
https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=1032-2929&m=dev&t=DqgBttaIC7RjH9Yc-1
https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=2423-846&m=dev&t=DqgBttaIC7RjH9Yc-1

- - - 

**Still need to do a figma design for the mobile overlay menu with connected wallets**

**Comment by babalicious-io** [comment]
Seems like the hamburger menu is stretched out

![Screenshot 2024-10-27 at 15 19 50](https://github.com/user-attachments/assets/979c80f8-7c2b-43e3-b08f-e5fa02df60e2)
Figma

![Screenshot 2024-10-27 at 15 20 37](https://github.com/user-attachments/assets/880cdc3c-95fd-4b42-9aed-79434e921b8a)
Dev site

![Screenshot 2024-10-27 at 15 22 55](https://github.com/user-attachments/assets/61021d93-5921-424e-9f0b-737822ba543e)
Left dev site // right figma

**Comment by reinamora137** [comment]
this is also related to #144

**Comment by reinamora137** [comment]
yeah i'm not seeing a change in the logo hover state:

https://www.figma.com/proto/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?page-id=0%3A1&node-id=4180-2445&node-type=instance&m=dev&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3246%3A13652&show-proto-sidebar=1&t=Re93JfqH7mVgP5CA-1

**Comment by reinamora137** [comment]
pending final review to close this issue based on : https://github.com/stampchain-io/BTCStampsExplorer/pull/183

also need final details on the hover state of the logo if required.

**Comment by reinamora137** [comment]
Details for Hover over on logo:

babalicious, [Oct 28, 2024 at 15:07:18]:
You can see it in action here
https://www.figma.com/proto/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=4166-2557&t=KwJgQ0uwhwA9OYoJ-1


Hover component for desktop
https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=4180-2445&m=dev&t=KwJgQ0uwhwA9OYoJ-1


You'll find all three versions in this section
https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=1032-1728&m=dev&t=KwJgQ0uwhwA9OYoJ-1

**Comment by babalicious-io** [comment]
Looking good on Desktop and Tablet !

On Mobile (768px and 568px-360px) the Menu open overlay (on click of hamburger menu) is off.
Looks like the layout may be swapped around on dev site.
Also note that the Connect Button and Social Icons change size.

![Screenshot 2024-10-28 at 22 43 56](https://github.com/user-attachments/assets/63657d26-e96b-450d-8b0d-5859b6f50323)

https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=1032-2929&m=dev&t=KwJgQ0uwhwA9OYoJ-1
https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=2423-846&m=dev&t=KwJgQ0uwhwA9OYoJ-1

**Comment by babalicious-io** [comment]
![Screenshot 2024-10-28 at 23 03 35](https://github.com/user-attachments/assets/1be51366-9572-48f6-bd17-59da20a7de0a)

Seems like the width of desktop on the dev site is not 1440px as in the figma design, or the left/right margins aren't 48px...
Top part of image is dev site, bottom figma.

**Comment by reinamora137** [comment]
this appears to be correct now with:

https://github.com/stampchain-io/BTCStampsExplorer/pull/199
