### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#172]
### Footer

The dev site is not updated to the latest figma designs.
Applies to all screen sizes.

https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=1032-1728&m=dev&t=DqgBttaIC7RjH9Yc-1

**Comment by reinamora137** [comment]
pending final review to close this issue based on : https://github.com/stampchain-io/BTCStampsExplorer/pull/183

**Comment by babalicious-io** [comment]
![Screenshot 2024-10-28 at 23 16 02](https://github.com/user-attachments/assets/58055ef3-934b-4f6d-8535-cabfa626417f)

**Desktop** - top part is dev site, bottom figma.

The font-sizing, spacing and font weight (links) are not sync'ed.

![Screenshot 2024-10-28 at 23 19 37](https://github.com/user-attachments/assets/c9cdf522-0432-47b6-b118-f10016307d96)

**Tablet**

![Screenshot 2024-10-28 at 23 22 32](https://github.com/user-attachments/assets/d3d62e38-886d-415e-b4f8-f8649623ba92)

**MobileLarge** (768px)

![Screenshot 2024-10-28 at 23 23 25](https://github.com/user-attachments/assets/4cace0d4-4cd8-4a1b-8253-ffabe9634f3a)

**MobileSmall** (568-360px)

- - -

- Hover state for social icons is #AA00FF
- The Discord invite (link) doesn't work for me.

![Screenshot 2024-10-28 at 23 28 46](https://github.com/user-attachments/assets/f2ac6834-7f56-46dd-97e2-0780462a14e6)

- How-To link needs a page (eg. .../how-to/), I'll have content for that page tomorrow-ish
- Press Kit link links to this url (in new tab) 
https://drive.google.com/drive/folders/18QsMTZ_ZII5FVxuAs2CLFoLdZE3NOdlT
- Media(About/Donate/Contact are pending and awaiting me

**Comment by reinamora137** [comment]
This is the new discord link: https://discord.gg/BRYRt4bH
