### ISSUE TITLE
Arrow Navigation

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#173]
There are two different sized versions of the Navigation Arrows - 36px//28px
I've made last minute adjustments to the font and icon sizes
Hover state - #aa00ff
Active/selected state - #660099

**Desktop/Tablet/MobileLarge** - 36px
https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=4444-4897&m=dev&t=DqgBttaIC7RjH9Yc-1

**MobileSmall (568px-360px)** - 28px
https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=4444-5490&m=dev&t=DqgBttaIC7RjH9Yc-1
https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=4444-5558&m=dev&t=DqgBttaIC7RjH9Yc-1

**Comment by babalicious-io** [comment]
![Screenshot 2024-10-28 at 23 39 22](https://github.com/user-attachments/assets/0f5ace7f-3aba-4dcb-8b6f-39fad07410ee)

The small versions of the Navigation Arrows - 28px - kicks in too early.
It should happen at 568px (not 768px)

Screenshot is MobileLarge - 768px - top part is the dev site and bottom figma

The hover state doesn't seem to work

**Comment by reinamora137** [comment]
looks like the hover state is still a pending issue on these

**Comment by reinamora137** [comment]
hover state appears to be working now. it's unclear if the differing sizes are implemented correctly?

**Comment by reinamora137** [comment]
TO-DO: 

 - Fix breakpoint for rendering down to 28px icons from the 36px at 568px (not the current 768px)
 - Add hoverstate for all icons (not implemented in figma) but specified here:
 
 Hover state - #aa00ff
 Active/selected state - #660099

**Comment by reinamora137** [comment]
this should be good now, moving to validation

**Comment by babalicious-io** [comment]
Perfect !

**Comment by reinamora137** [comment]
complete and validated
