### ISSUE TITLE
regression: dimensions and size recently removed from stamp detail page and 'creator_name' removed

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#178]
the prior display of dimensions and size were removed on the stamp detail page, and the 'BY' aka creator_name or creator is no longer displaying. it's a placeholder 'Stampchain' as the creator of all images

![image](https://github.com/user-attachments/assets/cec2487c-cfdd-4a91-9d9a-84128174ef0c)

**Comment by reinamora137** [comment]
related to other stamp detail issues: #145

**Comment by eliot1011** [comment]
I show the Stampchain if creator_name is empty
if current is wrong, what should I show instead of Stampchain ?

**Comment by reinamora137** [comment]
> I show the Stampchain if creator_name is empty if current is wrong, what should I show instead of Stampchain ?

The creator field. Same as before

**Comment by reinamora137** [comment]
Creator name /address is resolved

**Comment by reinamora137** [comment]
Still need to review why dimensions stopped working. That was functional previous and looks like that code did not change

**Comment by reinamora137** [comment]
dimensions and size resolved
