### ISSUE TITLE
Horizontal table scroll bar does not match figma 

### ISSUE THREAD

**Issue by StampBlaster5000** [stampchain-io/BTCStampsExplorer#179]
Current: Example found on stamp details window.
![image](https://github.com/user-attachments/assets/9a3381ef-3a61-4b2e-bdd9-640b7a491917)

Figma: 
![image](https://github.com/user-attachments/assets/3cb4ad9d-04af-41fb-b965-a5dc76933dbb)

**Comment by reinamora137** [comment]
Resolved
