### ISSUE TITLE
How-To Page Template

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#185]
More details here:

https://github.com/orgs/stampchain-io/discussions/31

the final text of the content will be handled after page creation, etc.

**Comment by reinamora137** [comment]
how-to link in the footer should link to this one

**Comment by babalicious-io** [comment]
> how-to link in the footer should link to this one

No, the footer link should link to an Overview page a la this

![Screenshot 2024-10-29 at 10 28 08](https://github.com/user-attachments/assets/27e054c9-aaea-4e6e-900f-f16d3e244de5)

It still is WIP

The Overview page will have a url that looks something like this
.../how-to/
.../manuals/

And the Template:
.../how-to/deploy-tokens/
.../manuals/deploy-tokens/

Makes sense ?

**Comment by reinamora137** [comment]
More details here: 

https://github.com/orgs/stampchain-io/discussions/31
