### ISSUE TITLE
Border on StampCard

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#191]
The border on the stampcard doesn't quite match

FIGMA:

![image](https://github.com/user-attachments/assets/ea7389b5-ca91-4fd8-b80c-29612de42459)

vs

![image](https://github.com/user-attachments/assets/5bf354f0-36fc-43a4-917e-104167b485e7)

and hover-over

![image](https://github.com/user-attachments/assets/40fbc52a-e5fa-47d3-a8c9-984f619b8c90)

**Comment by reinamora137** [comment]
this is all the stampcard components:

https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=1477-5689&m=dev

**Comment by babalicious-io** [comment]
Note that on mobile 568px resizing down to 360px

![Screenshot 2024-10-29 at 00 53 48](https://github.com/user-attachments/assets/0ade6fe7-8ca1-4463-a1e1-20df0a958c42)

Image padding scales down from 12px to 6px
Hover bg blur padding to bg card scales down from 6px to 4px
Padding for Sale Price (left) and Editions (right) scale down from 18px to 12px - to the edge of the BgCard
Creator addy displays fewer characters scaling down

We have a breakpoint at 420px being used on a couple of other components/page versions for scaling down (eg. the tokencards), this breakpoint can be used if needed.

![Screenshot 2024-10-29 at 00 51 03](https://github.com/user-attachments/assets/7eec671a-6f4e-4a75-ad02-ec833ce5893e)

**Comment by reinamora137** [comment]
the container looks ok now without the border, but the hover-over state is broken

**Comment by reinamora137** [comment]
created a new issue for the scaling question. Border is resolved.
