### ISSUE TITLE
Pagination Not Properly Functional on /wallet for Stamps

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#213]
going here: https://dev.bitcoinstamps.xyz/wallet/1GotRejB6XsGgMsM79TvcypeanDJRJbMtg

and clicking the next or second page icon on the pagination: 

![image](https://github.com/user-attachments/assets/7a5e9e55-d103-449a-b2c3-2c0d2643720f)

produces a page 2 with a limit of 1 param

https://dev.bitcoinstamps.xyz/wallet/1GotRejB6XsGgMsM79TvcypeanDJRJbMtg?page=2&limit=1&type=all&sortBy=DESC

and all pagination options are then removed/disabled

![image](https://github.com/user-attachments/assets/c2bf599c-9edf-4c18-a1b5-3087ea20a652)

**Comment by wichopy** [comment]
ill try this one

**Comment by reinamora137** [comment]
The pagination for the stamps is working after a recent update. However the src20card pagination is impacted by the stamp pagination as well. They need to be separated to work independently

**Comment by reinamora137** [comment]
The stampcards are displayed via stampsection so we have a reusable method to consistently display they. It is likely we need a similar technique for src-20. This may have been started for the home page. Needs review

**Comment by reinamora137** [comment]
just to clarify this is working for stamps, but there should likely be a second query parameter to handle sorting of the src-20 tokens.

**Comment by reinamora137** [comment]
closing for a new issue on the SRC-20 pagination issue
