### ISSUE TITLE
Hover State on StampCard missing purpleBright Border

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#220]
Hover state doesn't display the purpleBright border only the purpleBright bg blur...

It appears the padding and rounded edges may not be quite right as well

Current:

![image](https://github.com/user-attachments/assets/220be13d-e33a-408c-b134-e893963b249d)

should be: 

![image](https://github.com/user-attachments/assets/531497f1-eae3-4144-83bc-8346cad2be7d)

Refer to reference here:

https://www.figma.com/proto/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?page-id=0%3A1&node-id=3102-2780&node-type=frame&m=dev&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3102%3A2780&show-proto-sidebar=1&t=HWhEhW7A4gbILrvy-1

**Comment by reinamora137** [comment]
related #222

**Comment by babalicious-io** [comment]
Looking good
