### ISSUE TITLE
Src20 deploy errors (mobile OKX)

### ISSUE THREAD

**Issue by arwyn6969** [stampchain-io/BTCStampsExplorer#249]
Got these errors when I was trying to upload a deploy token. 

I tried twice with the images to make sure that I had a 420 size image I think ultimately the image size was correct but these were the errors that were returned and I don't understand! I will also add for further clarity that I was in the actual OKX app using the Discover feature on the browser and logging in in that manner. I don't think there is another way to do it from Mobile actually.

[image](https://github.com/user-attachments/assets/87651926-8324-4ac1-af94-2d50f9d7d9da)

**Comment by Jamesoliver000** [comment]
> Got these errors when I was trying to upload a deploy token.
> 
> I tried twice with the images to make sure that I had a 420 size image I think ultimately the image size was correct but these were the errors that were returned and I don't understand! I will also add for further clarity that I was in the actual OKX app using the Discover feature on the browser and logging in in that manner. I don't think there is another way to do it from Mobile actually.
> 
> [image](https://github.com/user-attachments/assets/87651926-8324-4ac1-af94-2d50f9d7d9da)


@arwyn6969 Thanks for posting the issue.
Your query would be best dealt with by the support team.

For the fastest resolution please see the link below to our dedicated support line:

Support : [Help Center](http://dextoolshub.com/)
