### ISSUE TITLE
Font Sizing on StampCard, ₿ icon, and conditional logic on stampcards

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#267]
Use the ₿ emoji or as otherwise specified in figma. See revisions below about conditional logic on displaying image type instead of price in certain scenarios.

**Comment by babalicious-io** [comment]
**Can we use conditional logic on the stampcards ?**

If a stamp is not listed, then display type (eg. JPG/PNG/HTML/SVG)
If stamp is listed then display price.

- - - 

![Screenshot 2024-11-12 at 13 45 25](https://github.com/user-attachments/assets/f544b4ff-686e-47fe-9ff7-07d32a4f5efa)
![Screenshot 2024-11-12 at 13 44 49](https://github.com/user-attachments/assets/296b8c3d-c86f-4a06-ad8a-3be679b2212f)

**Comment by babalicious-io** [comment]
I have updated the stampcards with the bitcoin icon
Unfortunately the font doesn't have a ₿ glyph, so it doesn't look so good - imo

![Screenshot 2024-11-12 at 14 57 10](https://github.com/user-attachments/assets/5386fbe1-4bc5-4e24-93a9-0d758f2ae055)
![Screenshot 2024-11-12 at 14 56 59](https://github.com/user-attachments/assets/ad505fd6-9a08-4765-a863-5a4c2be18583)

- - -

**On mobile Sm/Md** - Recent Sales stampcards
I have changed the text size for both stamp# and price - and changed the height of the BgCard

- - - 

https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=1477-5689&m=dev&t=XgQoR7PJTG69N6UY-1
