### ISSUE TITLE
SRC20Card Not Matching Figma. 

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#295]
Currently it is showing a progress bar for 100% minted items when it should not. it should also not be displaying the 'mint' button for these:

current:
<img width="1349" alt="image" src="https://github.com/user-attachments/assets/8e1c13a2-aa4d-4928-a8b4-fdefc9f6fd99">

vs figma:

<img width="988" alt="image" src="https://github.com/user-attachments/assets/b6672c01-630a-47a9-b675-0b001ac8b12c">

https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=2609-8440&m=dev

Will also need to validate it's displayed properly on the SRC20TrendingMints and PopularMints, wallet,  SRC20DeployTable, etc.

**Comment by wichopy** [comment]
looking at this. How do these values map to the values in the screen shot?

```
{
  tx_hash: string;
  block_index: number;
  p: string;
  op: string;
  tick: string;
  tick_hash: string;
  creator: string;
  creator_name: string | null;
  amt?: string | bigint;
  deci?: number;
  max?: string | bigint;
  lim?: string | bigint;
  destination: string;
  destination_name?: string;
  block_time: Date;
  status: string;
  row_num: number;
  progress?: string | null;
  email?: string;
  web?: string;
  tg?: string;
  x?: string;
  holders: number;
  floor_unit_price?: number;
  mcap?: number;
}
```

And what is the logic for when to show the mint button and progress bar vs when not to?

**Comment by reinamora137** [comment]
dev4pear is working on this one, but i'll add some details. 

the logic is mostly implemented with the mint button greyed out when fully minted for reference. 

if progress == 100 then it's fully minted out and don't display the progress bar aka design 2 on the bottom of the img. 
if email,web,tg,x - then display them
