### ISSUE TITLE
Stamping Tool

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#319]
### The page has been updated and changes pushed

![Screenshot 2024-11-20 at 00 33 17](https://github.com/user-attachments/assets/ca6d9c24-3391-4f8e-9f6f-f27e398505eb)

**There is one major issues that needs attention**

The advanced section toggle switch has two states
- CUSTOM CPID
- POSH

The Custom CPID option is not created/defined - this I haven't tried to figure out how to do, so someone else needs to fix this

![Screenshot 2024-11-20 at 00 33 49](https://github.com/user-attachments/assets/3cec6baa-3900-4e25-aef6-384796c15810)

↑ this should be Custom cpid

![Screenshot 2024-11-20 at 00 33 57](https://github.com/user-attachments/assets/18bf1e12-6ae1-4a87-8422-d7e9d167f13b)

↑ this is correct

![Screenshot 2024-11-20 at 00 34 30](https://github.com/user-attachments/assets/321fd650-3167-4ebc-85b1-c56efe045dd1)

↑ figma design - this is how it should look (the toggle color has been changed, so nevermind that)

**Comment by babalicious-io** [comment]
![Screenshot 2024-11-20 at 12 21 18](https://github.com/user-attachments/assets/4fb2b3fc-8310-4a6e-b9ce-69e512d859d5)

The STAMP button doesn't seem to work
Despite uploading image/entering edition numbers/agreeing to ToS I still cannot stamp

**Comment by babalicious-io** [comment]
![Screenshot 2024-11-20 at 23 46 52](https://github.com/user-attachments/assets/368e25ac-91f0-41a8-85d6-140c7f2e5055)


The items marked with orange need to be updated - all the code is in the recent PR
- we reverted back to BTC instead of the btc logo character
- DETAILS should be darker color and the up/down icon has been changed
- there should be styling code for the checkbox - if this is overwritten by the browser, let me know and I'll do another fix

I'll make a small update to make the input field characters uppercase and adjust text padding on mobileSm in next PR

**Comment by babalicious-io** [comment]
Great you sorted the STAMP button !!!

May I suggest using the outline button for the initial CONNECT WALLET and switching to flat button once connected (STAMP button).

CONNECT WALLET - buttonPurpleOutlineClassName
STAMP - buttonPurpleFlatClassName

Would be great to change the behaviour of the Mint/Deploy/Transfer pages to do the same.

**Comment by reinamora137** [comment]
also need to review the styling on the checkpox and the dropdown icon 

will create a new issue for the deploy/mint/transfer pages to function in the same way.

**Comment by dev4pear** [comment]
updated checkbox, and dropdown icon styles
updated CONNECT WALLET button style
