### ISSUE TITLE
Minting Tool

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#325]
**The minting tool has been updated with minor styling changes and pull request made** 

![Screenshot 2024-11-20 at 15 27 13](https://github.com/user-attachments/assets/1cf98755-8098-4224-9bc7-04ddca7f29c1)

I fiddled with the code to make the mint progress bar look (and behave) like the fee selector beneath, but can't get it to scale right
Please check lines 22-26 and adjust this so that the progress bar and fee selector are uniform

![Screenshot 2024-11-20 at 15 26 00](https://github.com/user-attachments/assets/3288650e-f120-42bd-906b-c99bd455dfc0)

- - -

There seems to be an issue with the backend
It gives this error, no matter what ticker is typed in

![Screenshot 2024-11-20 at 12 12 06](https://github.com/user-attachments/assets/c98ca4d4-0bcd-4e86-9ca7-5e4e4ca823ef)

Please also check that the image auto updates on ticker input - also the cursor pointer shouldn't change, since there is no user action possible

![Screenshot 2024-11-20 at 15 28 45](https://github.com/user-attachments/assets/6f642160-e040-4719-98a4-41c15e286989)

**Comment by reinamora137** [comment]
perhaps some minor details on this left, but looks good for now
