### ISSUE TITLE
How To modules

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#336]
![Screenshot 2024-11-20 at 20 46 21](https://github.com/user-attachments/assets/1c612a41-7678-4962-80fe-9b86f714a3ac)
![Screenshot 2024-11-20 at 20 45 09](https://github.com/user-attachments/assets/89c27263-2f62-4734-878a-1d810f4e5f06)
![Screenshot 2024-11-20 at 20 45 00](https://github.com/user-attachments/assets/dc02e1c6-9036-4082-9b51-dd1a440c0d82)

The Deploy page and Transfer page need to have their How-To modules/sections updated.
At present they are displaying the How-To module for minting

https://dev.bitcoinstamps.xyz/stamping/src20/deploy
https://dev.bitcoinstamps.xyz/stamping/src20/transfer

The module content also needs to be updated - check the modules PR

**Comment by dev4pear** [comment]
fixed Deploy & Transfer page to redirect to the proper How-To modules
