### ISSUE TITLE
How To page articles

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#337]
Most of the How To articles that Tony has written are not displayed.
The urls are in place, but no content is loaded/displayed.

https://dev.bitcoinstamps.xyz/howto/deploytoken
https://dev.bitcoinstamps.xyz/howto/mint
https://dev.bitcoinstamps.xyz/howto/getstamping

This page is displayed, but content is lacking, it's mainly dummytext
https://dev.bitcoinstamps.xyz/howto/transfer

This is the only this page that works properly
https://dev.bitcoinstamps.xyz/howto/leatherconnect

**Comment by reinamora137** [comment]
these are now all working. need more content for the transfer page still. Tony didn't get to that one it looks like
