### ISSUE TITLE
Stampcard padding

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#351]
The stampcard padding is off/missing on mobileSm (base) and mobileMd
This needs to be fixed

![Screenshot 2024-11-22 at 13 07 52](https://github.com/user-attachments/assets/0fa14cad-5c31-480a-acd1-e519b47724fc)
![Screenshot 2024-11-22 at 14 20 10](https://github.com/user-attachments/assets/435cc556-514c-4d3a-a0b6-1009236bcbe0)

**Comment by dev4pear** [comment]
added padding on mobileSm and mobileMd
