### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#354]
**Issues that need to be fixed up**

![Screenshot 2024-11-22 at 21 27 01](https://github.com/user-attachments/assets/5ac93ca4-6fe5-4b6c-a679-dc722d38d68f)

- **Carousel**

![Screenshot 2024-11-22 at 21 27 20](https://github.com/user-attachments/assets/315ebad1-348a-4a14-aeca-a8e66ede98cf)

- padding between **Fresh Posh Stamps** and **Recent Recursive**
`gap-3 mobileMd:gap-6 desktop:gap-9`
- Cutting Edge (collection bannercards) needs a subtitle // the cards need finetuning
Figma design ↓

![Screenshot 2024-11-22 at 21 47 04](https://github.com/user-attachments/assets/ce969d3c-76c1-4c55-89a4-85fb18759258)

Note that we have planned two sections of bannercards ↓

![Screenshot 2024-11-22 at 21 49 34](https://github.com/user-attachments/assets/c7ffc0aa-1d67-4c80-aa88-a25f871bfe88)

![Screenshot 2024-11-22 at 21 27 41](https://github.com/user-attachments/assets/c174d364-be5f-43c8-8ed8-cb1f45db764c)

- title and subtitle for SRC-20 section
- padding `gap-3 mobileMd:gap-6 desktop:gap-9`
Figma design ↓

![Screenshot 2024-11-22 at 21 53 00](https://github.com/user-attachments/assets/a55ae5d2-1bca-4ed5-8108-1d9fd92a21c3)

**Comment by dev4pear** [comment]
fixed all padding issues and layout issues except carousel
waiting for carousel update from other guy
