### ISSUE TITLE
Stamp Overview page

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#359]
![Screenshot 2024-11-23 at 00 39 09](https://github.com/user-attachments/assets/2b9600bc-17d3-49de-adea-070b606f28f0)

**Stamp Overview page** - issues needing attention
- sort button and filter button both need to have the icon colors updated to #8800CC
the border color is updated, but the icons seem to be png images, that I cannot change 
if you use svg icons you can easily change color with fill

![Screenshot 2024-11-23 at 00 27 37](https://github.com/user-attachments/assets/47f32af5-708b-47a7-92bd-dbfb5a27bd9d)

- on mobileSm/Md the stampcard padding is off
Mentioned [here](https://github.com/stampchain-io/BTCStampsExplorer/issues/351) as well
- the sort/filter/search buttons should be smaller on mobileSm/Md
Check [figma design](https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=1424-354&m=dev&t=fqkGMgN1S6e8k2AF-1) for reference ↓

![Screenshot 2024-11-23 at 00 48 26](https://github.com/user-attachments/assets/43631e41-f327-49f6-bee2-1019cdefc8f8)

**Comment by wichopy** [comment]
tackled the first point in https://github.com/stampchain-io/BTCStampsExplorer/pull/360

In follow up PR will work on the next 2 points 

> on mobileSm/Md the stampcard padding is off
> Mentioned https://github.com/stampchain-io/BTCStampsExplorer/issues/351 as well
> the sort/filter/search buttons should be smaller on mobileSm/Md
> Check [figma design](https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=1424-354&m=dev&t=fqkGMgN1S6e8k2AF-1) for reference ↓

**Comment by wichopy** [comment]
@babalicious-io when filters is expanded, the background is transparent. What color should it be?

![Screenshot 2024-11-23 at 2 29 39 PM](https://github.com/user-attachments/assets/70fd3bb6-380d-4e81-9b26-c834a4f6e036)

**Comment by babalicious-io** [comment]
Sorry @wichopy, I missed your question

Gradient from top to bottom
#080808 100%
#080808 80%

**Comment by wichopy** [comment]
attempted to fix here but not sure why tail wind is not building my custom background 

https://github.com/stampchain-io/BTCStampsExplorer/pull/409
