### ISSUE TITLE
Wallet page - Dropdown overlay

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#371]
![Screenshot 2024-11-24 at 11 57 13](https://github.com/user-attachments/assets/cb3153a3-9a35-4b34-8f45-a6f5425d8efd)

**Wallet page has been updated and PR created**
https://github.com/stampchain-io/BTCStampsExplorer/pull/370

![Screenshot 2024-11-24 at 11 57 56](https://github.com/user-attachments/assets/b45c37e5-fb2a-40c6-9d38-8ddd035f7621)

![Screenshot 2024-11-24 at 11 58 10](https://github.com/user-attachments/assets/c4eade19-2d49-44ef-bf6e-f8b483717398)

![Screenshot 2024-11-24 at 11 59 00](https://github.com/user-attachments/assets/b4450993-f802-493b-b6f9-6ced6900db5d)

![Screenshot 2024-11-24 at 11 58 29](https://github.com/user-attachments/assets/19740791-f821-4ac0-b608-ed9c8d481590)

![Screenshot 2024-11-24 at 11 58 54](https://github.com/user-attachments/assets/aa809b94-242d-47bb-abf8-aa05f847c08f)

All button icons need to be checked, cause their size is inconsistent, both the button and icons
There should be two sizes of buttons - mobileSm/Md and mobileLg/tablet/desktop
Some buttons use png others svg icons
The filter menus need to be updated to look like figma design

note: this is related to https://github.com/stampchain-io/BTCStampsExplorer/issues/359#issuecomment-2495630304

![Screenshot 2024-11-24 at 12 10 20](https://github.com/user-attachments/assets/50ede268-5bec-45c5-9dbb-ffff4963fc23)

![Screenshot 2024-11-24 at 12 10 35](https://github.com/user-attachments/assets/6df35097-163d-464b-9e4b-795eaf0d1c2e)

![Screenshot 2024-11-24 at 12 10 30](https://github.com/user-attachments/assets/3db3f2a8-dfda-4895-a56f-fef08c7706a1)

The color is not right in figma, but button/icon sizes are

https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=3246-13652&m=dev&t=I49LVTeToFz0L710-1

**Comment by babalicious-io** [comment]
![Screenshot 2024-11-24 at 12 22 59](https://github.com/user-attachments/assets/9a82fae4-eb40-4410-9daf-6fdde6c128ee)

There are specific tokencards for the wallet

The ones in use are the ones designed for the stamp overview page
The wallet tokencards build upon the others

Note that figma design tickerName color isn't updated and the text that is #999999 should be #CCCCCC - like on the other elements of the page

![Screenshot 2024-11-24 at 12 18 33](https://github.com/user-attachments/assets/b7cbc158-95a8-4ac1-b1bb-9883dcfa65e5)

https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=4645-3439&m=dev&t=I49LVTeToFz0L710-1

**Comment by babalicious-io** [comment]
![Screenshot 2024-11-24 at 12 24 28](https://github.com/user-attachments/assets/52fa3b71-d6ca-4d1b-b98c-73c5c845b1b0)

Figma design 

Copy icon needs to be swapped
Eye icon should be #999999
Check the weight (thickness) of the icons - history icon seems fat compared to the others on dev site

**Comment by babalicious-io** [comment]
![Screenshot 2024-11-24 at 12 31 09](https://github.com/user-attachments/assets/fd19e758-8b3b-42a2-94fa-091e16a00b14)

Listingscard

Value is off, needs a decimal/comma somewhere

**Comment by babalicious-io** [comment]
![Screenshot 2024-11-24 at 12 33 09](https://github.com/user-attachments/assets/b07169ff-290e-4c43-917b-d97147afce76)

Pagination

If there is only one page of content can we just omit the pagination all together
(there shouldn't be a VIEW ALL button either)

**Comment by StampBlaster5000** [comment]
Suggestion src20 wallet table-in wallet profile, to be in listed format-with small image holder for token images
![image](https://github.com/user-attachments/assets/6de4e403-e2bc-432e-8336-efa72368105a)

**Comment by wichopy** [comment]
I was struggling a bit with the button icons, they don't have a defined width and height, its just padding that wraps around the internal SVG. There needs to be a reusable button component.

**Comment by babalicious-io** [comment]
If you are in doubt, the size is
mobileSm/Md - 28px button // 14px icon
mobileLg/tablet/desktop - 36px button // 18px icon
All icons are bold version

To be found here
https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=706-2870&m=dev&t=dvAvnM9JSBN0moXZ-1
Have just updated the colors (for those components), so figma design is in sync with dev site

The more reusable components the better - imo

**Comment by babalicious-io** [comment]
There is a Button.tsx file with some button components - this could be used
Would be great to get all buttons in one place !

**Comment by babalicious-io** [comment]
We also have some button styling hiding in Styles.ts - fyi

**Comment by babalicious-io** [comment]
> ![Screenshot 2024-11-24 at 12 24 28](https://private-user-images.githubusercontent.com/142315627/389268408-52fa3b71-d6ca-4d1b-b98c-73c5c845b1b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MTEyMzcsIm5iZiI6MTczMzQxMDkzNywicGF0aCI6Ii8xNDIzMTU2MjcvMzg5MjY4NDA4LTUyZmEzYjcxLWQ2Y2EtNGQxYi1iOThjLTczYzVjODQ1YjFiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQxNTAyMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNTg4MjUzOWNkMjI4YmY3YzM1ZjYxNjlhOTZhMjEyNDVmYTkyOWJmMDBmYjJhNzY5MWU1ZjgwNjM4NTBiNjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.y4LyAze0LdL0_XiqGU-CQJ-amUa7SULOazMI2qnzoJg)
> 
> Figma design ↑
> 
> Copy icon needs to be swapped Eye icon should be #999999 Check the weight (thickness) of the icons - history icon seems fat compared to the others on dev site

**FIXED**
