### ISSUE TITLE
Collections Overview page

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#373]
The page is almost ready, just a couple of things relating to the featured collections banners that need to be finished

![Screenshot 2024-11-24 at 14 50 09](https://github.com/user-attachments/assets/8e27ad62-b8c7-4465-aa85-27caf4a43422)

![Screenshot 2024-11-24 at 14 50 18](https://github.com/user-attachments/assets/f81e6e89-39c2-4081-b580-90698c279d96)

They are missing preview images, hover state and the text should be uppercase

![Screenshot 2024-11-24 at 14 54 46](https://github.com/user-attachments/assets/b46f30d4-7c2b-4e9d-92d8-bfa97bf1d581)

Figma design ↑

https://www.figma.com/design/Os9UawIAetoFAqwkNKHN9j/Stampchain-web?node-id=957-19001&m=dev&t=vGz1ly42xhUWoWPH-1

**Comment by babalicious-io** [comment]
https://github.com/stampchain-io/BTCStampsExplorer/pull/372

**Comment by babalicious-io** [comment]
you need to decide on which collections to feature

**Comment by dev4pear** [comment]
fixed preview image, text uppercase, and hover state issues
now, it is showing first 3 and 4 collections to featured ones manually, so you need to decide on which collections to feature
