### ISSUE TITLE
Error page - 404 redirect

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#388]
I have suggested new text for the error page, I found the initial one a little sad/heavy.

On Internal Server Error (and displaying a blank white page with unstyled text) I suggest displaying the error404 page instead.

When accessing a url that doesn't exist, the site redirects to home, dunno if it's intentional, seems like a catchAll setting. I tried to change this, but got lost in claude's circular logic and couldn't get it to work. So I haven't been able to see the changes made.

Would be good to display a **Sorry can't find what you are looking for** type page. We could use this page for undefined/unfindable searches as well.

![Screenshot 2024-11-28 at 11 08 12](https://github.com/user-attachments/assets/1af9e1d2-2811-408f-9cbc-a746a75f81a4)
This redirects to /home

**Comment by reinamora137** [comment]
![image](https://github.com/user-attachments/assets/1a60ef73-4c34-40f3-92b2-ea3f3a233ba6)
