### ISSUE TITLE
Stamp Transfer tool - dropdown selector

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#393]
**The Stamp Transfer tool needs a little attention**

![Screenshot 2024-11-28 at 01 45 43](https://github.com/user-attachments/assets/31a60af2-a736-4ed9-8f02-221392018c2e)

The selectable stamps dropdown menu just seems to display dummy text
The stamp image should update on select

**Comment by itttm127** [comment]
I am getting the data from wallet page using this endpoint: /api/v2/src20/balance/address.
and I am showing the stamp.stamp and whenever change the stamp select, I showed the  stamp_url for image.

**Comment by reinamora137** [comment]
sorry I was confused on this one:

we have the src20 transfer:
https://dev.bitcoinstamps.xyz/stamping/src20/transfer

vs the stamp transfer this was related to. so the emdpoint i had above on /src/20/balances was incorrect as it should use the /api/v2/stamps/balance endpoint

**Comment by reinamora137** [comment]
the stamp transfer portion is looking good

![image](https://github.com/user-attachments/assets/4e597947-31f3-4847-8cf7-12b3a99f4e2b)
