### ISSUE TITLE
Mint page

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#394]
The Mint page tool functionality is looking great

![Screenshot 2024-11-28 at 13 20 24](https://github.com/user-attachments/assets/8a426fe9-a1f4-47a2-be8b-d26d4b2ff641)

There is a minor bug with the dropdown menu, that seems to get stuck and not always disappear after selecting

**Comment by itttm127** [comment]
I fixed this part
whenever you input the text, it will show the changed the dropdown menu
and it's working on mobile version too.
