### ISSUE TITLE
Holders component / Pie chart

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#404]
![Screenshot 2024-11-29 at 23 27 57](https://github.com/user-attachments/assets/7e1c402e-52f1-4a3f-b094-b3cd332abe77)

![Screenshot 2024-11-29 at 23 27 44](https://github.com/user-attachments/assets/363351e2-78ca-4797-a1b4-cd705dae5bfd)

Holders table needs some finetuning
- placement is perfect without scrollbar
- when scrollbar is displayed then it (and scrollbar) should shift a little left (pr-6 kind of thing)
- can the scrollbar be moved down a little (mt-6/pt-6)

HoldersGraph.tsx

The pie chart 
- the tooltips aren't displayed - should display addy on hover
- animate on load

PieChart.tsx
[GitHub doc](https://github.com/chartjs/Chart.js/blob/master/docs/charts/doughnut.md)

**Comment by wichopy** [comment]
is it just me? I am seeing an overlap of the text when growing the screen.

https://github.com/user-attachments/assets/49289dc3-a67f-4436-a716-54055ce695dc

**Comment by wichopy** [comment]
potential fix, please try it out.

https://github.com/stampchain-io/BTCStampsExplorer/pull/410

**Comment by wichopy** [comment]
for holders table, adding tooltip

https://github.com/stampchain-io/BTCStampsExplorer/pull/412

I thought we could jus use the tailwind auto layout for the table, which removes the need for abbreviating, but feel free to give feedback if thats what we want. I figured if we want a tool tip to show the whole address, why not just show the whole address when you have enough screen real estate?

**Comment by reinamora137** [comment]
looks good now! closing this one
