### ISSUE TITLE
Missing Buy Button

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#434]
![Screenshot 2024-12-05 at 15 57 41](https://github.com/user-attachments/assets/6993b4b9-c1a6-4eff-9916-f7a66a01e5a7)

On the Stamp Detail page the BUY button is missing despite a dispenser being open
It is present in the code 

StampInfo.tsx
line 205

**Comment by reinamora137** [comment]
note:
- this only shows when there is an open dispenser(s)
- if there are multiple dispensers it keys off of the lowest price dispenser for the buy modal
- this was working previously so probably something simple
