### ISSUE TITLE
Wallet Page SRC-20 Details not Displaying

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#439]
When on the wallet page the src-20 token details do not display

https://dev.bitcoinstamps.xyz/wallet/bc1qhhv6rmxvq5mj2fc3zne2gpjqduy45urapje64m?src20_page=2&src20_limit=8&type=all&sortBy=DESC

![image](https://github.com/user-attachments/assets/b2bc0212-8654-40cd-a2e5-ac08c59224d6)

It should look like the  /src20 page and use the same shared components. in particular the fully minted and not-fully minted components
https://dev.bitcoinstamps.xyz/src20

![image](https://github.com/user-attachments/assets/a2cf83c0-142e-46ee-a429-085adc66edfd)

**Comment by babalicious-io** [comment]
https://github.com/stampchain-io/BTCStampsExplorer/issues/371#issuecomment-2495950153

This is mentioned earlier
There is a specific tokencard design for the wallet page
The figma design is not up to date regarding font color and size, but the layout/build/structure is correct and should be implemented

**Comment by reinamora137** [comment]
now no tokens are displayed.


![image](https://github.com/user-attachments/assets/41e33627-51a2-4590-a3ef-dc65390beda7)


https://dev.bitcoinstamps.xyz/wallet/bc1qhhv6rmxvq5mj2fc3zne2gpjqduy45urapje64m
