### ISSUE TITLE
Mint Token - auto populate

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#446]
![Screenshot 2024-12-05 at 21 23 00](https://github.com/user-attachments/assets/7a51976f-455e-4bdc-96bd-c99c74f35726)

When user clicks a mintingToken tokencard and is taken to the Mint page the tokenTicker field should autopopulate and image presented.
The ticker info is present in the url string so the data is passed and just needs to be pulled in somewhere/somehow in the minting tool

![Screenshot 2024-12-05 at 21 23 56](https://github.com/user-attachments/assets/f7afd36e-59b7-4632-904b-ba83066fbfdd)

**Comment by reinamora137** [comment]
Also related, when searching for ASXAI it doesn't show in the dropdown, or populate the image / amt when typed

![image](https://github.com/user-attachments/assets/bebb98cf-68d2-4226-a86d-ff61b39c1da0)
