### ISSUE TITLE
Bitname SRC101 mint page

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#459]
**A page needs to be created for src101 minting - aka bitname register**

There is a file created here:
islands/stamping/src101/mint/MintContent.tsx

It doesn't have to be placed there, if there is another/better logic to apply.
A route must be created, so the page can be accessed in a browser.

**Comment by reinamora137** [comment]
https://dev.bitcoinstamps.xyz/stamping/src101/mint created

will need some love, we can default the toaddress to the logged in wallet, or create a new field.

Also errrors on calculating and populating the feerates that needs some love

**Comment by reinamora137** [comment]
https://github.com/stampchain-io/BTCStampsExplorer/commit/cef6a04d94103e5da41fa965f716f1a87888e823
