### ISSUE TITLE
No Tokens displayed in wallet /src20 section

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#461]
no tokens are displayed.

![image](https://github.com/user-attachments/assets/41e33627-51a2-4590-a3ef-dc65390beda7)

https://dev.bitcoinstamps.xyz/wallet/bc1qhhv6rmxvq5mj2fc3zne2gpjqduy45urapje64m

_Originally posted by @reinamora137 in https://github.com/stampchain-io/BTCStampsExplorer/issues/439#issuecomment-2526277762_

```
Uncaught (in promise) ReferenceError: props is not defined
    at chunk-A7XVBXTU.js:1:1383
    at Array.map (<anonymous>)
    at M.O [as constructor] (chunk-A7XVBXTU.js:1:1281)
    at M.cn [as render] (chunk-LAJCUF7P.js:1:8699)
    at I (chunk-LAJCUF7P.js:1:6201)
    at L (chunk-LAJCUF7P.js:1:1441)
```

**Comment by FerrariDEVo** [comment]
@reinamora137 For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
