### ISSUE TITLE
Background gradients

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#481]
The background Gradient Top and Bottom are fixed on the screen/viewport (following the user on scroll) instead of fixed on page

Top gradient should disappear up when user scrolls down (and the header logo+navMenu disappear up)
Bottom gradient should first appear when user scrolls to bottom (and views the footer)

It used to work properly before the last mayor update
I have tried changing the positioning in the code
styles.css - line 151/210
but have not succeeding in fixing the issue

**Comment by itttm127** [comment]
I removed the style properties on div tag.
