### ISSUE TITLE
Stamp detail - Sales tab

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#484]
![Screenshot 2024-12-11 at 13 41 16](https://github.com/user-attachments/assets/14bbf6f6-e8b5-40c4-a24f-e04075a8d340)

The sales tab on the Stamp Detail page doesn't display data properly

Shouldn't it display total amount of sales ?

StampRelatedInfo.tsx
StampSales.tsx

**Comment by itttm127** [comment]
In this case, what's the correct expected value for sales ?
because as I checked the backend, I think there is no issues for getting value.
so I hope you to explain more details.

**Comment by reinamora137** [comment]
> In this case, what's the correct expected value for sales ? because as I checked the backend, I think there is no issues for getting value. so I hope you to explain more details.

Simply the count of sales. I thought it was in there previously, but something broke

**Comment by reinamora137** [comment]
this is resolved

![image](https://github.com/user-attachments/assets/d31cf2ad-82ca-4c8d-b25b-b06a7b0c761c)
