### ISSUE TITLE
search on src20 page

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#492]
/src20

![image](https://github.com/user-attachments/assets/a7a5f71a-3e15-4345-8657-1f1c7875cf30)

not working, should drop down with matching token names.

**Comment by itttm127** [comment]
it's showing the tokens that progress is not 100%
I have to keep this function or change ?

**Comment by reinamora137** [comment]
Correct the search is for all tokens

**Comment by reinamora137** [comment]
Should be showing a dropdown widow of items that match anyway

**Comment by itttm127** [comment]
I think this is search component
so if I change this, every search option will show all tokens
or there is special page that I need to show tokens that progress is not 100% ?

**Comment by reinamora137** [comment]
It shouldn’t be an issue with fully minted or unminted here https://bitcoinstamps.xyz/src20 

also this is a shared component which is used elsewhere but we need to remove the view all when on the /src20 page  

![image](https://github.com/user-attachments/assets/adf57a88-28e0-4554-8cd3-c3cf8aac517c)

**Comment by itttm127** [comment]
we need to sort by when type is trending on src20 page ?

**Comment by reinamora137** [comment]
If easily done. Some of those filter options may not be possible with the current api and db setup.
