### ISSUE TITLE
Stamp transfe (send)  not working (leather wallet / Desktop)

### ISSUE THREAD

**Issue by arwyn6969** [stampchain-io/BTCStampsExplorer#501]
<img width="1507" alt="Screenshot 2024-12-16 at 10 24 17" src="https://github.com/user-attachments/assets/9b2b40df-7dec-4107-82c0-c34ae2c897ae" />

transfer button not activating anything.. maybe is connected inccorectly through stacks?

**Comment by reinamora137** [comment]
https://github.com/stampchain-io/BTCStampsExplorer/pull/521

**Comment by reinamora137** [comment]
also showing frontend errors

```
[Violation] Forced reflow while executing JavaScript took 41ms
[Violation] Forced reflow while executing JavaScript took 30ms
[Violation] Forced reflow while executing JavaScript took 41ms
[Violation] Forced reflow while executing JavaScript took 40ms
[Violation] Forced reflow while executing JavaScript took 62ms
[Violation] 'setInterval' handler took 53ms
[Violation] 'setInterval' handler took 61ms
[Violation] 'setInterval' handler took 50ms
```

**Comment by reinamora137** [comment]
Fixed in commit: https://github.com/stampchain-io/BTCStampsExplorer/commit/e6bc5b7c297845bef8529e027cb1f66eeabd9fcd
