### ISSUE TITLE
Home landing page - Trending Tokens section is missing

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#528]
The entire section of trending minting tokens on the home page is not displaying

The header is there and the loader displays, but no tokencards show up

**Comment by Musk101131** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by reinamora137** [comment]
error calling: https://dev.bitcoinstamps.xyz/api/internal/src20/trending?limit=5&page=undefined&sortBy=undefined

{"error":"Error fetching trending tokens","status":"error","code":"INTERNAL_ERROR","details":{}}

**Comment by reinamora137** [comment]
resolved in attached commit. the undefined page and sortBy being passed was puking things
