### ISSUE TITLE
'ALL' text on drop down menu is overlapping with the SRC-20 Tokens header in the menu bar

### ISSUE THREAD

**Issue by reinamora137** [stampchain-io/BTCStampsExplorer#530]
![image](https://github.com/user-attachments/assets/dd0beb66-8727-4e49-bd61-d3ee0b5ed3c2)

![image](https://github.com/user-attachments/assets/e71f99d0-1881-4e30-89d8-e44cc3266b3d)

**Comment by babalicious-io** [comment]
I don't see it on my end
![Uploading Screenshot 2024-12-18 at 16.37.30.png…]()

**Comment by reinamora137** [comment]
must have been a transient error. not seeing anymore
