### ISSUE TITLE
Buy modal - cannot close

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#565]
**The buy popup modal cannot close**

<img width="470" alt="Screenshot 2024-12-20 at 16 10 23" src="https://github.com/user-attachments/assets/af350220-5efe-49b5-9e5f-42c14dafd537" />

Neither via 
- cancel
-  X (close)
- onClick outside of modal

There is a conflict with the tooltip of some sort
the tooltip displays (fee selector) on hover
but once user clicks (to attempt to close) it doesn't display again

This should be updated

**Comment by reinamora137** [comment]
resolved
