### ISSUE TITLE
Home page - Trending Mints section is not displaying

### ISSUE THREAD

**Issue by babalicious-io** [stampchain-io/BTCStampsExplorer#566]
<img width="647" alt="Screenshot 2024-12-20 at 16 13 52" src="https://github.com/user-attachments/assets/af579263-5470-4eec-b768-78a5ad111b06" />

**The section displaying the top minting tokencards is missing on the landingpage**
The subTitle heading is displayed, but the content is not

**Comment by reinamora137** [comment]
Part of ongoing v0.10 refactor. Will be resolved for v0.11.0
