### ISSUE TITLE
SRC20 trending error -An error occurred during route handling or page rendering.

### ISSUE THREAD

**Issue by arwyn6969** [stampchain-io/BTCStampsExplorer#571]
https://dev.bitcoinstamps.xyz/src20?type=trending
<img width="1501" alt="Screenshot 2024-12-21 at 21 09 17" src="https://github.com/user-attachments/assets/b358618a-8271-48e7-93e9-5ee351dd0431" />

An error during route handling or page rendering usually means there's a problem with the JavaScript code responsible for displaying the content of the page. This could be due to a variety of reasons, such as:

Incorrect data fetching: The code might be trying to access data that doesn't exist or is in the wrong format.
Logic errors: There might be a bug in the code that handles the routing or rendering process.
Component failures: A specific component on the page might be throwing an error, preventing the rest of the page from rendering correctly.
External dependencies: A problem with an external library or API that the page relies on could be causing the error. To debug this, we need to identify the source of the error. We can start by checking the browser's console for any error messages.

Code to execute

according to. berowser ai

const data = {
  consoleErrors: [],
};

// Capture console errors
const originalConsoleError = console.error;
console.error = (...args) => {
  data.consoleErrors.push(args.join(' '));
  originalConsoleError.apply(console, args);
};

// Trigger a potential error by forcing a re-render
try {
  $0.parentElement.removeChild($0);
  $0.parentElement.appendChild($0);
} catch (error) {
  data.consoleErrors.push(error.message);
}

// Restore original console.error
console.error = originalConsoleError;

**Comment by reinamora137** [comment]
WIP in refactor.
