### ISSUE TITLE
forwarding error for emoji token src20

### ISSUE THREAD

**Issue by arwyn6969** [stampchain-io/BTCStampsExplorer#572]
https://dev.bitcoinstamps.xyz/src20/%F0%9F%9B%B8

When clicking the box for the relevant ufo token as seen in pic, from ( https://dev.bitcoinstamps.xyz/src20?sortBy=DESC)

 the following link it goes to (included above is broken
<img width="1211" alt="Screenshot 2024-12-21 at 21 36 44" src="https://github.com/user-attachments/assets/35f3c8dd-4b6f-461f-bb7f-0aa6783dc3a6" />
<img width="1508" alt="Screenshot 2024-12-21 at 21 37 21" src="https://github.com/user-attachments/assets/661cfe33-006a-4f5d-ada1-8af2064f6202" />

**Comment by reinamora137** [comment]
there is a pending fix for this waitingn to be merged into dev
