### ISSUE TITLE
Pagination Not Working Correctly

### ISSUE THREAD

**Issue by arwyn6969** [stampchain-io/BTCStampsExplorer#573]
Description: The page buttons at the bottom of the page always display the newest stamps regardless of the page button selected. The issue was observed on [this URL](https://dev.bitcoinstamps.xyz/stamp?type=classic&stamps_page=5).

Steps Taken
Reviewed Relevant Files:

globals.d.ts: Defined interfaces for pagination types.
routes/api/v2/stamps/dispensers/index.ts: Implemented handler for paginated requests.
lib/controller/stamp.ts: Fetches stamps data with pagination, sorting, and filtering logic.
lib/utils/util.ts: Contains the pagination utility function.
Identified Potential Issues:

Checked URL parameters extraction.
Verified sorting and filtering logic.
Reviewed recent changes in components/PageControl.tsx.
Next Steps
Modify the code to ensure pagination displays the correct stamps per page.
Test the changes in a local or staging environment.
Apply the fix to the production environment and monitor.

**Comment by reinamora137** [comment]
there is a pending fix for this waiting to be merged into dev.
